language: python
python:
- "2.7"
- "3.3"
- "3.6"
install:
- pip install pyflakes
- pip install pycodestyle
- pip install python-afl
env:
- TRAVIS=TRUE
script:
- pyflakes src/*.py
- pyflakes tests/*.py
- pycodestyle src/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle src/static/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle tests/*.py --max-line-length 180 --statistics
- python setup.py install
- nosetests --verbose

