dist: trusty
sudo: True
language: python
python:
- "2.7"
- "3.3"
- "3.6"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then true ${CYTHON_VERSION:=0.26.1}; fi
- cython_suffix=${CYTHON_VERSION:+==$CYTHON_VERSION}
install:
- git clone --depth=50 --branch=master https://github.com/agroce/afl.git agroce/afl
- make -C agroce/afl install PREFIX=~/.local
- sudo echo core >/proc/sys/kernel/core_pattern
- pip install --verbose cython${cython_suffix}
- pip install pyflakes
- pip install pycodestyle
- pip install python-afl
env:
- TRAVIS=TRUE CYTHON_VERSION=
script:
- pyflakes src/*.py
- pyflakes tests/*.py
- pycodestyle src/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle src/static/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle tests/*.py --max-line-length 180 --statistics
- python setup.py install
- nosetests --verbose

