language: python
python:
- "2.7"
- "3.3"
- "3.6"
install:
- pip install pyflakes
- pip install pycodestyle
env:
- TRAVIS=TRUE
script:
- python setup.py install
- nosetests --verbose
- pyflakes src/*.py
- pycodestyle src/*.py --max-line-length 180 --ignore W605,E722,E741,W503,W504,E704
- pycodestyle src/static/*.py --max-line-length 180 --ignore W605,E722,E741,W503,W504,E704