language: python
dist: trusty
sudo: false
python:
- "2.7"
- "3.6"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then true ${CYTHON_VERSION:=0.26.1}; fi
- cython_suffix=${CYTHON_VERSION:+==$CYTHON_VERSION}
install:
- git clone --depth=50 --branch=master https://github.com/agroce/afl.git agroce/afl
- make -C agroce/afl install PREFIX=~/.local
- pip install --verbose cython${cython_suffix}
- pip install pyflakes
- pip install pycodestyle
- pip install python-afl
- pip install arrow
- pip install bidict
- pip install bintrees
- pip install biopython
- pip install rsa
- pip install sympy
- pip install z3
- pip install tensorflow
env:
- TRAVIS=TRUE CYTHON_VERSION= AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=TRUE
script:
- pyflakes src/*.py
- pyflakes tests/*.py
- pycodestyle src/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle src/static/*.py --max-line-length 180 --statistics --ignore W503,W504,E704
- pycodestyle tests/*.py --max-line-length 180 --statistics
- python setup.py install
- nosetests --verbose

